In [123]:
import pandas as pd
import matplotlib as plt

In [124]:
df_main = pd.read_csv("datasets/fact_bookings.csv")
df_date = pd.read_csv('datasets/dim_date.csv')
df_hotels = pd.read_csv('datasets/dim_hotels.csv')
df_rooms = pd.read_csv('datasets/dim_rooms.csv')
df_agg_bookings = pd.read_csv('datasets/fact_aggregated_bookings.csv')

In [125]:
df_main.sample(10)

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
28476,May202217559RT111,17559,19-05-22,20-05-22,21-05-22,3.0,RT1,journey,NaN,Cancelled,12155,4862
56293,Jun082217560RT214,17560,7/6/2022,8/6/2022,9/6/2022,1.0,RT2,tripster,3.0,Checked Out,15300,15300
68251,Jun162216559RT23,16559,12/6/2022,16-06-22,21-06-22,2.0,RT2,others,NaN,Checked Out,15300,15300
121003,Jul212219562RT313,19562,15-07-22,21-07-22,22-07-22,2.0,RT3,makeyourtrip,5.0,Checked Out,18000,18000
112143,Jul152217563RT47,17563,14-07-22,15-07-22,16-07-22,1.0,RT4,others,5.0,Checked Out,32300,32300
120941,Jul212219561RT27,19561,15-07-22,21-07-22,26-07-22,2.0,RT2,makeyourtrip,3.0,Checked Out,13500,13500
42802,May292218560RT13,18560,26-05-22,29-05-22,1/6/2022,1.0,RT1,makeyourtrip,NaN,Checked Out,6500,6500
90128,Jul012217562RT16,17562,30-06-22,1/7/2022,6/7/2022,1.0,RT1,others,NaN,No Show,11050,11050
16211,May112217560RT18,17560,11/5/2022,11/5/2022,12/5/2022,1.0,RT1,makeyourtrip,5.0,Checked Out,11050,11050
117387,Jul182219558RT16,19558,18-07-22,18-07-22,23-07-22,2.0,RT1,direct online,1.0,Checked Out,9750,9750

In [126]:
# fixing date to consistent formats
df_main["booking_date"] = pd.to_datetime(df_main["booking_date"],format = "mixed")
df_main["check_in_date"] = pd.to_datetime(df_main["check_in_date"],format = "mixed")
df_main["checkout_date"] = pd.to_datetime(df_main["checkout_date"],format = "mixed")

In [127]:
# checking no of rows and columns
df_main.shape

(134590, 12)

In [128]:
# checking each rows and columns for null value and each column data type 
df_main.info()
#  leaving ratings as it is ! and checking on guests column

<class 'pandas.DataFrame'>
RangeIndex: 134590 entries, 0 to 134589
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booking_id         134590 non-null  str
 1   property_id        134590 non-null  int64
 2   booking_date       134590 non-null  datetime64[us]
 3   check_in_date      134590 non-null  datetime64[us]
 4   checkout_date      134590 non-null  datetime64[us]
 5   no_guests          134587 non-null  float64
 6   room_category      134590 non-null  str
 7   booking_platform   134590 non-null  str
 8   ratings_given      56683 non-null   float64
 9   booking_status     134590 non-null  str
 10  revenue_generated  134590 non-null  int64
 11  revenue_realized   134590 non-null  int64
dtypes: datetime64[us](3), float64(2), int64(3), str(4)
memory usage: 12.3 MB

In [129]:
#checking errors on guests count
df_main.no_guests[df_main.no_guests <0]

# cutting out these rows(since there are less rows)!
df_main = df_main[df_main.no_guests >=0]
df_main.shape #nearly 12 rows have been cutoff

(134578, 12)

In [130]:
#checking if nulls are same in whole column
df_main.ratings_given.unique()

array([nan,  5.,  4.,  3.,  1.,  2.])

                                              Moving on to clean other data sets

In [131]:
# cleaning data 
# fixing date to consistent formats
df_agg_bookings["check_in_date"] = pd.to_datetime(df_agg_bookings["check_in_date"],format = "mixed")

# checking for errors in booking and capacity:
df_agg_bookings[df_agg_bookings.successful_bookings > df_agg_bookings.capacity]
# cutoff the rows with such errors
# df_agg_bookings = df_agg_bookings[df_agg_bookings.successful_bookings < df_agg_bookings.capacity]

      property_id check_in_date room_category  successful_bookings  capacity
3           17558    2022-05-01           RT1                   30      19.0
12          16563    2022-05-01           RT1                  100      41.0
4136        19558    2022-06-11           RT2                   50      39.0
6209        19560    2022-07-02           RT1                  123      26.0
8522        19559    2022-07-25           RT1                   35      24.0
9194        18563    2022-07-31           RT4                   20      18.0

In [132]:
# checking data ready for analysis
df_agg_bookings.sample(20)

      property_id check_in_date room_category  successful_bookings  capacity
3564        18558    2022-06-05           RT3                   18      26.0
4869        17563    2022-06-18           RT3                   13      16.0
6884        18559    2022-07-08           RT4                    8      19.0
4696        17562    2022-06-16           RT4                    3       6.0
1489        17559    2022-05-15           RT4                    9      14.0
7491        18563    2022-07-14           RT4                   10      18.0
6867        16563    2022-07-08           RT3                   12      20.0
1783        18561    2022-05-18           RT4                    5       9.0
6430        16561    2022-07-04           RT2                   14      24.0
5828        17558    2022-06-28           RT2                   26      50.0
8498        17561    2022-07-24           RT4                    3       4.0
4819        18561    2022-06-18           RT1                   28      33.0
5505        16558    2022-06-25           RT1                   14      19.0
3961        18559    2022-06-09           RT3                    8      23.0
158         16558    2022-05-02           RT3                    5       8.0
2703        19563    2022-05-28           RT1                   22      30.0
53          18562    2022-05-01           RT3                   28      29.0
8379        19561    2022-07-23           RT4                    4       7.0
8459        17560    2022-07-24           RT3                   16      25.0
7368        18559    2022-07-13           RT3                   10      23.0

In [133]:
# cleaning data 
df_date["date"] = pd.to_datetime(df_date["date"],format = "mixed")
df_date["day_type"] = df_date["day_type"].apply(lambda x :"weekday" if x == "weekeday" else x)

In [134]:
df_date.sample(10)

         date  mmm yy week no day_type
77 2022-07-17  Jul 22    W 30  weekend
35 2022-06-05  Jun 22    W 24  weekend
80 2022-07-20  Jul 22    W 30  weekday
71 2022-07-11  Jul 22    W 29  weekday
12 2022-05-13  May 22    W 20  weekday
52 2022-06-22  Jun 22    W 26  weekday
48 2022-06-18  Jun 22    W 25  weekend
33 2022-06-03  Jun 22    W 23  weekday
29 2022-05-30  May 22    W 23  weekday
90 2022-07-30  Jul 22    W 31  weekend

In [135]:
df_date.sample(20)

         date  mmm yy week no day_type
22 2022-05-23  May 22    W 22  weekday
19 2022-05-20  May 22    W 21  weekday
12 2022-05-13  May 22    W 20  weekday
51 2022-06-21  Jun 22    W 26  weekday
25 2022-05-26  May 22    W 22  weekday
91 2022-07-31  Jul 22    W 32  weekend
65 2022-07-05  Jul 22    W 28  weekday
33 2022-06-03  Jun 22    W 23  weekday
16 2022-05-17  May 22    W 21  weekday
77 2022-07-17  Jul 22    W 30  weekend
34 2022-06-04  Jun 22    W 23  weekend
85 2022-07-25  Jul 22    W 31  weekday
6  2022-05-07  May 22    W 19  weekend
48 2022-06-18  Jun 22    W 25  weekend
3  2022-05-04  May 22    W 19  weekday
73 2022-07-13  Jul 22    W 29  weekday
64 2022-07-04  Jul 22    W 28  weekday
69 2022-07-09  Jul 22    W 28  weekend
71 2022-07-11  Jul 22    W 29  weekday
20 2022-05-21  May 22    W 21  weekend

                                                  1. REVENUE ANALYSIS

In [136]:
# total revenue generated :
print("Total Revenue Generated :",df_main["revenue_generated"].sum())

# total revenue generated :
print("Total Revenue Realized :",df_main["revenue_realized"].sum())

Total Revenue Generated : 2069545455
Total Revenue Realized : 1708603879

                                                Revenue by city

In [137]:
# Merging:
main_with_city = pd.merge(df_main,df_hotels,on = "property_id")

# checking with main df shape to verify if duplicates :
main_with_city.shape

# checking null sum for verification :
main_with_city.isnull().sum()

booking_id               0
property_id              0
booking_date             0
check_in_date            0
checkout_date            0
no_guests                0
room_category            0
booking_platform         0
ratings_given        77899
booking_status           0
revenue_generated        0
revenue_realized         0
property_name            0
category                 0
city                     0
dtype: int64

In [138]:
Rev_by_city = main_with_city.groupby("city")["revenue_realized"].sum().sort_values(ascending = False)
Rev_by_city

city
Mumbai       668602231
Bangalore    420383550
Hyderabad    325179310
Delhi        294438788
Name: revenue_realized, dtype: int64

Insight: Mumbai and Bangalore drives the most business

                                                            Revenue by Hotel

In [139]:
Rev_by_hotel = main_with_city.groupby("property_name")["revenue_realized"].sum().sort_values(ascending = False)
Rev_by_hotel

property_name
Atliq Exotica    320291568
Atliq Palace     304081863
Atliq City       285798439
Atliq Blu        260851922
Atliq Bay        260022118
Atliq Grands     211471234
Atliq Seasons     66086735
Name: revenue_realized, dtype: int64

Insight:

                                                         Revenue by Room category

In [140]:
Rev_by_Rcategory = main_with_city.groupby("category")["revenue_realized"].sum().sort_values(ascending = False)
Rev_by_Rcategory

category
Luxury      1052636842
Business     655967037
Name: revenue_realized, dtype: int64

Insight:

                                                          2. OCCUPANCY ANALYSIS

                                           * Occupancy rate = bookings / capacity

In [141]:

df_agg_bookings["Occupancy_Rate"] = (df_agg_bookings.successful_bookings / df_agg_bookings.capacity)

occ_rate =df_agg_bookings.groupby("room_category")["Occupancy_Rate"].mean().sort_values(ascending = False)

occ_by_room = pd.merge(occ_rate,df_rooms, left_on ="room_category",right_on = "room_id")
occ_by_room

   Occupancy_Rate room_id    room_class
0        0.593002     RT4  Presidential
1        0.582242     RT1      Standard
2        0.580402     RT2         Elite
3        0.580283     RT3       Premium

Insight:

                                            * Which hotels are underperforming?

In [142]:
hotels = pd.merge(df_agg_bookings,df_hotels,on = "property_id")

hotel_perfm =hotels.groupby("property_name")["Occupancy_Rate"].mean().sort_values(ascending = False)
hotel_perfm

property_name
Atliq Blu        0.631230
Atliq Palace     0.599437
Atliq City       0.599057
Atliq Exotica    0.579049
Atliq Bay        0.578746
Atliq Grands     0.551135
Atliq Seasons    0.445064
Name: Occupancy_Rate, dtype: float64

Insight:

                                            * Weekday vs weekend occupancy

In [143]:
week_enq = pd.merge(hotels,df_date, left_on = "check_in_date",right_on = "date")
week_enq.groupby("day_type")["Occupancy_Rate"].mean().sort_values(ascending = False)

day_type
weekend    0.742410
weekday    0.518223
Name: Occupancy_Rate, dtype: float64

Insight:

                                                  3. CUSTOMER BEHAVIOR

                                                       Cancellation rate

In [144]:
cancel_rate = (df_main.booking_status == 'Cancelled').mean()*100
print("Cancellation Rate :",cancel_rate)

Cancellation Rate : 24.83095305324793

In [145]:
cancelled = df_main[df_main.booking_status == 'Cancelled']
cancelled.shape

(33417, 12)

                                                     Booking platforms performance

In [146]:
by_platform = df_main.groupby("booking_platform")["booking_id"].count().sort_values(ascending=False)
by_platform

booking_platform
others            55062
makeyourtrip      26896
logtrip           14754
direct online     13376
tripster           9630
journey            8106
direct offline     6754
Name: booking_id, dtype: int64

Insight: